version: "3.9"
services:
  fact-server:
    build: .
    image: fact-model
    container_name: fact_model_server
    environment:
      MODEL_TYPE: gpt2
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    command: python fact_server.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  retrain:
    build: .
    image: fact-model
    container_name: fact_model_retrain
    environment:
      MODEL_TYPE: gpt2
    volumes:
      - .:/workspace
    entrypoint: bash -c "python prepare_dataset.py && python train_fact_model.py"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
