services:
  fact-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MODEL_TYPE=gpt2
    restart: unless-stopped
